[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
sqlx = { version = "0.8.2", features = ["sqlite"] }
tokio = { version = "1.41.1", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
